name: Delete files from folder

on:
  push:
    branches:
      - main

jobs:
  delete_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete files
        run: |
          # Navigate to the specified folder
          cd main/combined

          # Delete all files in the folder while keeping the folder itself
          rm -rf ./*

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Delete all files from specified folder"
          git push
