name: Generate Sidebar YAML

on:
  push:
    branches:
      - main  # Anpassen Sie den Branch-Namen entsprechend Ihrem Repository

jobs:
  generate_sidebar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyYAML  # Installieren Sie die erforderlichen Abhängigkeiten

    - name: Create static values
  run: |
    echo '- title: sidebar
  product: Software Tools for NFDI4Cat
  folders:
    - title:
        output: pdf
        type: frontmatter
        folderitems:
          - title:
              url: /titlepage.html
              output: pdf
              type: frontmatter
          - title:
              url: /tocpage.html
              output: pdf
              type: frontmatter
    - title: NFDI4Cat
      output: web, pdf
      folderitems:
        - title: Overview
          url: /mydoc_NFDI4Cat_Overview.html
          output: web, pdf
    - title: Introduction to Github Pages
      output: web, pdf
      folderitems:
        - title: Overview
          url: /mydoc_Introduction_to_GitHub_Pages.html
          output: web, pdf
    - title: Software Tools
      output: web, pdf
      folderitems:
        - title: Landing Page for Software Tools
          url: /mydoc_LandingPage.html
          output: web, pdf
          subfolders:
            - title: Software
              output: web
              subfolderitems:
                - title: Protege
                  url: /n4cat_soft_Protege.html
                  output: web
                - title: Owlready2
                  url: /mydoc_SoftwareTools_Protege.html
                  output: web' > sidebar_static.yaml
    echo "..." >> sidebar_static.yaml

      - name: Generate Sidebar
        run: |
          python generate_sidebar.py
          cat sidebar_static.yaml sidebar_data.yaml > sidebar_combined.yaml

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "matze2402"
          git add sidebar_combined.yaml  # Anpassen des Dateinamens der kombinierten YAML-Datei
          git commit -m "Update sidebar YAML"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
